version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: vocab_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vocab_network

  bot:
    build: .
    container_name: vocab_bot
    restart: always
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      MY_TG_ID: ${MY_TG_ID}
      TOKEN_VOCAB: ${TOKEN_VOCAB}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    volumes:
      - vocab_data:/app/data
    networks:
      - vocab_network

volumes:
  postgres_data:
  vocab_data:

networks:
  vocab_network: